### ISSUE TITLE
[1.16.5 suggestion] remove status effect entirely

### ISSUE THREAD

**Issue by superon** [HellsingDarge/CompactStatusEffects#10]
could we have an option to remove the status effect entirely from the inventory view? :)
i did try:
effectsPerColumn = 0
..
but that seems to remove to inventory causing a never ending hang

**Comment by superon** [comment]
although -1 did a thing
![Screen Shot 2022-02-17 at 20 41 18](https://user-images.githubusercontent.com/5957924/154567305-ed7a6a8d-ab3f-4be0-b172-edb342064379.png)

**Comment by HellsingDarge** [comment]
1.16.5 is no longer supported. The issue was fixed in v2.1.1

**Comment by superon** [comment]
:) i "fixed" it by setting the margin to about 180
