### ISSUE TITLE
Add Timers to main hud

### ISSUE THREAD

**Issue by Chrisblox** [HellsingDarge/CompactStatusEffects#4]
Having the timers also appear in the main HUD and not just the inventory would be really useful,
another thing that would be nice is if the potion effect level is one to not display the level number.

Great mod Thanks!

**Comment by HellsingDarge** [comment]
With MC's capability to do font rendering, it'll be rather hard without using an external library... I could make the background change colour depending on duration (like OnlyName display)

**Comment by Chrisblox** [comment]
For the level number would it instead be possible to display as roman numerals like how Minecraft usually shows it?

**Comment by HellsingDarge** [comment]
I could, but I don't want to fight with it having a proper centre placement...

**Comment by HellsingDarge** [comment]
Both level displays issues were addressed in 1.2.2
Can't add timer for in-game HUD, due to mixin limitation for lambda. Once it's possible, I'll revisit it
