### ISSUE TITLE
Inventory screen gets pushed to the right

### ISSUE THREAD

**Issue by FewerFlaws** [HellsingDarge/CompactStatusEffects#6]
If this is an intentional feature to make room for more effects would it be possible to make it configurable?  It compresses REI quite a bit.

![2021-01-09_13 55 49](https://user-images.githubusercontent.com/75643699/104109486-4a8ed480-5283-11eb-9827-15c52a9d5cfb.png)

**Comment by HellsingDarge** [comment]
The GUI shift is the same as the vanilla one in all modes, I'll see what I can do
And probably butcher config screen while at it...

**Comment by FewerFlaws** [comment]
Oh, does vanilla do that?  I really appreciate that you're trying to address it then =]

**Comment by HellsingDarge** [comment]
Addressed in 1.3.0
