### ISSUE TITLE
[Crash/Bug] Opening inventory

### ISSUE THREAD

**Issue by ghost** [HellsingDarge/CompactStatusEffects#7]
**Description:** Opening inventory generate a crash.
**Logs:** https://pastebin.com/LwfRHYut

**Comment by HellsingDarge** [comment]
Workaround before the fix: opening settings menu (through ModMenu) should prevent this

**Comment by SZUMASTER** [comment]
I another way that work: I'm changed overlay_render in Xaero_minimap ; o

**Comment by ghost** [comment]
That's true, thanks, waiting for release fix

**Comment by HellsingDarge** [comment]
Fixed in v1.4.1 (and v2.0.1)
