### ISSUE TITLE
1.18 Issues

### ISSUE THREAD

**Issue by xanthian** [HellsingDarge/CompactStatusEffects#9]
![image](https://user-images.githubusercontent.com/7688001/147824540-1b5b4c97-aeb2-4d62-93bb-7d30957b479b.png)

Moving it to the left overlaps the crafting book.
Whilst leaving the REI exclusion on the right.

Could you possibly add functionality to disable it completely from the left and the right

**Comment by HellsingDarge** [comment]
Forgot this book even exists...
Nothing I can do about REI Exclusions zones, they're added by REI itself with no way to indicate that they shouldn't. It's something that has to be done on REI side
And what do you mean by completely disabling it?

**Comment by xanthian** [comment]
I thought REI exclusion zones are done within the mod??
[https://github.com/HellsingDarge/CompactStatusEffects/blob/master/src/main/kotlin/me/hellsingdarge/compactstatuseffects/StatusEffectsExclusions.kt](https://github.com/HellsingDarge/CompactStatusEffects/blob/master/src/main/kotlin/me/hellsingdarge/compactstatuseffects/StatusEffectsExclusions.kt)


I prefer to use the top right display of 'buffs/effects' but the one next to the player GUI is pointless and takes up screen space.
Just an option to toggle the player GUI effect display on or off.

**Comment by HellsingDarge** [comment]
REI adds them only for vanilla single column display, mine - to account for my display modules
